const packageConfig = {
    'patterns': [
        "setup/**",
        "!requirements.txt",
        "!.serverless/**",
        "!venv/**",
        "!node_modules/**",
        "!.idea/**",
        "!node_modules**",
        "!package.json",
        "!package-lock.json",
        "!Pipfile",
        "!Pipfile.lock",
        "!log.txt",
        "!README.md",
        "!ruff.toml",
        "!scripts/**",
        "!resources/**",
        "!__pycache__/**",
        "!.github",
        "!.gitignore",
        "!.pre-commit-config.yaml",
        "!.prettierignore",
        "!.prettierrc.json",
        "!.prettierignore",
        "!.ruff_cache",
        "!.vscode",
        "!scripts",
        "!.env",
        "!.isort.cfg",
        "!ruff.toml",
        "!serverless.ts",
        "!serverless-tsconfig.json",
        "!tsconfig.json",
        "!.pre-commit-config.yaml",
        "!.python-version",
        "!README.md"
    ]
}

export default packageConfig;
